-- Create replies table for AskAGrandfriend
CREATE TABLE IF NOT EXISTS replies (
    reply_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(user_id),
    content TEXT NOT NULL,
    author_name VARCHAR(100),
    author_type VARCHAR(50), -- 'student' or 'grandparent'
    is_approved BOOLEAN DEFAULT FALSE, -- For 'Grandfriend Approved Best Answer'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE replies ENABLE ROW LEVEL SECURITY;

-- Public Access Policies (Matching questions table for prototype)
CREATE POLICY "Public Read Replies" ON replies FOR SELECT USING (true);
CREATE POLICY "Public Insert Replies" ON replies FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Delete Replies" ON replies FOR DELETE USING (true);
