-- Create table for storing Boomerang meetup history
CREATE TABLE IF NOT EXISTS meetup_history (
    history_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user1_id INTEGER NOT NULL,
    user2_id INTEGER NOT NULL,
    met_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    duration_seconds INTEGER DEFAULT 0,
    FOREIGN KEY (user1_id) REFERENCES users(user_id),
    FOREIGN KEY (user2_id) REFERENCES users(user_id)
);
