-- Add user_id to questions table to track ownership
-- Run this in your Supabase SQL Editor if the column doesn't exist

-- If table doesn't exist (basic structure)
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    category VARCHAR(50),
    author_name VARCHAR(100),
    author_type VARCHAR(50),
    is_anonymous BOOLEAN DEFAULT FALSE,
    user_id INTEGER REFERENCES users(user_id), -- Link to users table
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- If table exists but missing user_id
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'questions' AND column_name = 'user_id') THEN
        ALTER TABLE questions ADD COLUMN user_id INTEGER REFERENCES users(user_id);
    END IF;
END $$;
