-- RESET Replies Table (Sub-Reply Version)
-- WARNING: This deletes all existing replies!

DROP TABLE IF EXISTS replies CASCADE;

CREATE TABLE replies (
    reply_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id UUID NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(user_id), -- INTEGER/BIGINT
    
    -- Sub-Reply Support
    parent_reply_id BIGINT REFERENCES replies(reply_id) ON DELETE CASCADE,
    
    content TEXT NOT NULL,
    author_name VARCHAR(100),
    author_type VARCHAR(50), 
    
    -- Reaction System (Only for top-level replies mostly, but schema supports generally)
    reaction VARCHAR(20) DEFAULT NULL, -- 'favourite', 'love', 'like'
    coins_awarded INTEGER DEFAULT 0,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE replies ENABLE ROW LEVEL SECURITY;

-- Public Access Policies
CREATE POLICY "Public Read Replies" ON replies FOR SELECT USING (true);
CREATE POLICY "Public Insert Replies" ON replies FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Delete Replies" ON replies FOR DELETE USING (true);
CREATE POLICY "Public Update Replies" ON replies FOR UPDATE USING (true);
